# Generated by Django 3.0.7 on 2020-08-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endPoint', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=256)),
                ('posted_DateTime', models.DateTimeField()),
                ('likes', models.IntegerField()),
                ('contents', models.TextField()),
            ],
        ),
    ]
